// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/farnham-home/LightTrust.tsx": () => import("../components/mockups/farnham-home/LightTrust.tsx"),
  "./components/mockups/farnham-home/RefinedNavy.tsx": () => import("../components/mockups/farnham-home/RefinedNavy.tsx"),
  "./components/mockups/farnham-home/WarmEditorial.tsx": () => import("../components/mockups/farnham-home/WarmEditorial.tsx")
};
